---
  - hosts: my_servers
    become: true
    tasks:
      - name: Crear archivo de prueba de conexión
        ansible.builtin.file:
          path: /home/ubuntu/prueba_conexion.txt
          state: touch  